VaalbaraApp/urls.py
from django.urls import path, include, re_path
from django.views.static import serve
from django.contrib import admin
from django.conf import settings
from . import views


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.dashboard, name="dashboard"),
    path('about/', views.about),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('ivm/', include('ivm.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ivm/urls.py
from django.urls import path
from . import views

app_name = 'ivm'

urlpatterns = [
    # Displays all inventories: /ivm/
    path('', views.list_inventories, name='inventory_manager'),

    path('partners/', views.list_partners, name='page_partners'),
    path('partners/<int:partner_id>/', views.partner_detail_panel, name='partner_detail'),
    path('partners/add', views.add_partner, name='add_partner'),
    path('partners/edit/<int:partner_id>/', views.edit_partner, name='edit_partner'),
    path('partners/delete/<int:partner_id>', views.delete_partner, name='delete_partner'),

    path('transactions/', views.list_transactions, name='transactions'),
    path('transactions/add/', views.add_transaction, name='add_transaction'),
    path('transactions/edit/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    path('transactions/delete/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('transactions/authorize/<int:transaction_id>/', views.authorize_transaction, name='authorize_transaction'),
    path('transactions/reject/<int:transaction_id>/', views.reject_transaction, name='reject_transaction'),
    path('transactions/complete/<int:transaction_id>/', views.complete_transaction, name='complete_transaction'),
    path('transactions/pdf/<int:transaction_id>/', views.file_pdf_transaction, name='transaction_pdf'),
    path('transactions/<int:transaction_id>/', views.transaction_details, name='transaction_detail'),

    path('items/add/', views.add_item, name='add_item'),
    path('items/add/<slug:inventory_slug>/', views.add_item, name='add_item_with_slug'),
    path('items/edit/<int:item_id>/', views.edit_item, name='edit_item'),
    path('items/delete/<int:item_id>/', views.delete_item, name='delete_item'),

    path('item-detail-panel/<int:item_id>/', views.item_detail_panel, name='item_detail_panel'),
    path('<slug:inventory_slug>/', views.inventory_details, name='inv_page'),
    path('<slug:inventory_slug>/<int:item_id>/', views.item_details, name='item_page'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.tasks_list, name='tasks_list'),
    path('new/', views.new_task, name='new_task'),
    path('<int:task_id>/', views.details_task, name='task_page'),
]

tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.conf import settings
from ivm.models import Transaction

User = get_user_model()

class Task(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)
    completion_deadline = models.DateTimeField(null=True, blank=True)
    completion_date = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="tasks_given")
    task_for = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="tasks")
    is_complete = models.BooleanField(default=False)

    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, null=True, blank=True, related_name="tasks")

    @property
    def is_overdue(self):
        return timezone.now() > self.completion_deadline
    
    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from .models import Task
from django.contrib.auth import get_user_model
User = get_user_model()

class CreateTask(forms.ModelForm):
    title = forms.CharField(
        label="Tiêu đề",
        widget=forms.TextInput(attrs={'class': 'form-textinput'})
    )
    task_for = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        label='Giao nhiệm vụ cho',
        widget=forms.SelectMultiple(attrs={'class': 'form-select'}),
    )
    body = forms.CharField(
        required=False,
        label="Thông tin",
        widget=forms.Textarea(attrs={'class': 'form-textarea', 'rows': 3})
    )
    completion_deadline = forms.DateTimeField(
        label='Hạn hoàn thành',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-datetime'}, format='%Y-%m-%dT%H:%M')
    )
    class Meta:
        model = Task
        fields = ['title','body','completion_deadline', 'task_for']

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Task
from .forms import CreateTask

# Create your views here.
@login_required(login_url='/users/login/')
def tasks_list(request):
    tasks = Task.objects.all().order_by('-creation_date')
    return render(request, 'tasks/tasks_list.html', {'tasks': tasks})

@login_required(login_url='/users/login/')
def details_task(request, task_id):
    task = Task.objects.get(id=task_id)
    return render(request, 'tasks/details_task.html', {'task': task})

@login_required(login_url='/users/login/')
def new_task(request):
    if request.method == 'POST':
        form = CreateTask(request.POST, request.FILES)
        if form.is_valid():
            task_new = form.save(commit=False)
            task_new.created_by = request.user
            task_new.creation_date = timezone.now()
            task_new.save()
            return redirect('tasks:tasks_list')
    else:
        form = CreateTask()
    return render(request, 'tasks/new_task.html', {'form': form})

tasks/templates/tasks/details_task.html
{% extends 'layout.html' %}


{% block title %}
Nhiệm vụ
{% endblock %}

{% block page_title %}
Nhiệm vụ
{% endblock %}

{% block nav_left %}
<a class="btn btn-jade" href="{% url 'tasks:tasks_list' %}">&lt</a>
{% endblock %}

{% block content %}
<section class="detail-body">
    <section class="detail-extra">
        <h3>{{ task.title }}</h3>
        <div class="detail-row">
            <label>Tạo bởi:</label>
            <span>{{ task.created_by }}</span>
        </div>
        <div class="detail-row">
            <label>Dành cho:</label>
            <span>{{ task.task_for }}</span>
        </div>
        <div class="detail-row">
            <label>Thông tin:</label>
            <span>{{ task.body }}</span>
        </div>
        <div class="detail-row">
            <label>Hạn hoàn thành:</label>
            <span>{{ task.completion_deadline|date:"m/d/Y H:i" }}</span>
        </div>
    </section>
</section>
{% endblock %}

tasks/templates/tasks/new_task.html
{% extends 'layout.html' %}


{% block title %}
Tạo nhiệm vụ
{% endblock %}
{% block page_title %}
Tạo nhiệm vụ
{% endblock %}

{% block content %}
<form class="form" action="{% url 'tasks:new_task' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="main-form">
        {{ form }}
    </section>
    <section class="form-actions">
        <button class="form-submit">Submit</button>
    </section>

</form>
{% endblock %}

tasks/templates/tasks/tasks_list.html
{% extends 'layout.html' %}


{% block title %}
Bảng nhiệm vụ
{% endblock %}
{% block page_title %}
Bảng nhiệm vụ
{% endblock %}

{% block content %}
<section class="actions-bar-wrapper">
    <section class="list-body">
        {% for task in tasks %}
        <article class="list-item">
            <h2><a href="{% url 'tasks:task_page' task_id=task.id %}">{{ task.title }}</a></h2>
            <p>Được tạo vào {{ task.creation_date|date:"d/m/Y" }} bởi {{ task.created_by }}</p>
            <p>{{ task.body }}</p>
        </article>
        {% empty %}
        Không còn nhiệm vụ
        {% endfor %}
    </section>

    <section class="actions-bar">
        <a href="{% url 'tasks:new_task' %}">
            <button class="btn btn-jade">+</button>
        </a>
    </section>
</section>
{% endblock %}